services:

  app:
    container_name: spring-boot-app
    image: spring-boot-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=spring_security
      - DB_USERNAME=username
      - DB_PASSWORD=password
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    container_name: postgres-sql
    image: postgres:17.5
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: spring_security
    volumes:
      - postgres:/data/postgres
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:

networks:
  app-network: